### ISSUE TITLE
Where can descriptor_mapping_tastes.csv be found.

### ISSUE THREAD

**Issue by Saket-Kr** [RoaldSchuring/wine_food_pairing#1]
Thge csv file named, "descriptor_mapping_tastes.csv" is used in the given program. But neither it is given in the repo, nor anything is said regarding where it can be found. Please look into this asap. Thanks.

**Comment by Saket-Kr** [comment]
Please at least let me know if the dataset isn't openly available.

**Comment by RoaldSchuring** [comment]
Hi Saket, apologies for the delay in addressing the issue you surfaced above. I have added the missing file you mentioned and have uploaded the raw dataset to Kaggle (see README for link). 

Is there anything in particular you are still missing?

**Comment by Saket-Kr** [comment]
I have what I needed. A big thank for looking into it.
